from __future__ import annotations

from pathlib import Path


def read_env_file(path: Path) -> list[str]:
    if not path.exists():
        return []

    return path.read_text(encoding="utf-8").splitlines()


def write_env_file(path: Path, lines: list[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    content = "\n".join(lines).rstrip("\n") + "\n"
    path.write_text(content, encoding="utf-8")


def upsert_env_values(path: Path, values: dict[str, str]) -> None:
    """Insert or update keys in a .env file while preserving other entries."""
    lines = read_env_file(path)
    remaining = dict(values)
    updated_lines: list[str] = []

    for line in lines:
        stripped = line.strip()
        if not stripped or stripped.startswith("#") or "=" not in line:
            updated_lines.append(line)
            continue

        key, _ = line.split("=", 1)
        key = key.strip()
        if key in remaining:
            updated_lines.append(f"{key}={remaining.pop(key)}")
        else:
            updated_lines.append(line)

    if remaining:
        if updated_lines and updated_lines[-1].strip():
            updated_lines.append("")
        updated_lines.append("# cTrader Open API OAuth tokens (generated by login.py)")
        for key, value in remaining.items():
            updated_lines.append(f"{key}={value}")

    write_env_file(path, updated_lines)
